[package]
name = "greetme"
version = "0.1.0"
authors = ["Jo Phillips <joxphillips@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17"
clicolors-control = "1.0.1"
rand = "0.7"
